[package]
name = "rust-vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.38.0", default-features = false, features = ["linked", "debug", "std"] }
ash-window = "0.13.0"
winit = { version = "0.30.5", features = ["rwh_06"] }